### ISSUE TITLE
[Bug] Incompatibility with Entity Texture Features and Entity Model Features; stuck on loading screen - 1.21 & 1.20.4

### ISSUE THREAD

**Issue by meowinqq** [daWinzig/entity-separator#3]
When attempting to load this mod (latest version) alongside EMF and ETF (latest versions), the game does not progress past the Mojang loading screen. Although the background music can be heard and it's possible to click on the title screen menu buttons, the loading screen persists indefinitely. Tested on 1.21 and 1.20.4, same result between both iterations. 

I've no clue whether this issue can be resolved here or if it's an issue exclusively within EMF and ETF -- my apologies if I've reported this in the wrong place!

**Comment by daWinzig** [comment]
The problem seems to be that ETF and this mod both try to redirect vanilla's `EntityRenderer::getTextureLocation` in `LivingEntityRenderer::getRenderType`. I don't know if there is a possibility for either mod to resolve this conflict.

The only thing I can think of is removing the custom texture feature completely.
